/** Australian merchant seed rules — priority ascending, first match wins. */

export type SeedRule = {
  priority: number
  matchType: 'contains' | 'starts_with' | 'regex' | 'exact_merchant'
  pattern: string
  categoryPath: [string, string?] // parent, optional child
}

export const AU_MERCHANT_SEED_RULES: SeedRule[] = [
  { priority: 10, matchType: 'contains', pattern: 'WOOLWORTHS', categoryPath: ['Food', 'Groceries'] },
  { priority: 10, matchType: 'contains', pattern: 'COLES', categoryPath: ['Food', 'Groceries'] },
  { priority: 10, matchType: 'contains', pattern: 'ALDI', categoryPath: ['Food', 'Groceries'] },
  { priority: 10, matchType: 'contains', pattern: 'IGA ', categoryPath: ['Food', 'Groceries'] },
  { priority: 10, matchType: 'contains', pattern: 'HARRIS FARM', categoryPath: ['Food', 'Groceries'] },
  { priority: 20, matchType: 'contains', pattern: 'MENULOG', categoryPath: ['Food', 'Takeaway & Delivery'] },
  { priority: 20, matchType: 'contains', pattern: 'UBER EATS', categoryPath: ['Food', 'Takeaway & Delivery'] },
  { priority: 20, matchType: 'contains', pattern: 'DOORDASH', categoryPath: ['Food', 'Takeaway & Delivery'] },
  { priority: 20, matchType: 'contains', pattern: 'DELIVEROO', categoryPath: ['Food', 'Takeaway & Delivery'] },
  { priority: 25, matchType: 'contains', pattern: 'MCDONALD', categoryPath: ['Food', 'Restaurants & Cafes'] },
  { priority: 25, matchType: 'contains', pattern: 'KFC', categoryPath: ['Food', 'Restaurants & Cafes'] },
  { priority: 25, matchType: 'contains', pattern: 'GUZMAN', categoryPath: ['Food', 'Restaurants & Cafes'] },
  { priority: 25, matchType: 'contains', pattern: 'STARBUCKS', categoryPath: ['Food', 'Restaurants & Cafes'] },
  { priority: 30, matchType: 'contains', pattern: 'LIQUORLAND', categoryPath: ['Food', 'Alcohol'] },
  { priority: 30, matchType: 'contains', pattern: 'DAN MURPHY', categoryPath: ['Food', 'Alcohol'] },
  { priority: 30, matchType: 'contains', pattern: 'BWS', categoryPath: ['Food', 'Alcohol'] },
  { priority: 40, matchType: 'contains', pattern: 'BP ', categoryPath: ['Transport', 'Fuel'] },
  { priority: 40, matchType: 'contains', pattern: 'AMPOL', categoryPath: ['Transport', 'Fuel'] },
  { priority: 40, matchType: 'contains', pattern: 'SHELL ', categoryPath: ['Transport', 'Fuel'] },
  { priority: 40, matchType: 'contains', pattern: '7-ELEVEN', categoryPath: ['Transport', 'Fuel'] },
  { priority: 40, matchType: 'contains', pattern: '7 ELEVEN', categoryPath: ['Transport', 'Fuel'] },
  { priority: 40, matchType: 'contains', pattern: 'CALTEX', categoryPath: ['Transport', 'Fuel'] },
  { priority: 45, matchType: 'contains', pattern: 'UBER TRIP', categoryPath: ['Transport', 'Public Transport'] },
  { priority: 45, matchType: 'contains', pattern: 'UBER *TRIP', categoryPath: ['Transport', 'Public Transport'] },
  { priority: 45, matchType: 'contains', pattern: 'TRANSPORT FOR NSW', categoryPath: ['Transport', 'Public Transport'] },
  { priority: 45, matchType: 'contains', pattern: 'TRANSLINK', categoryPath: ['Transport', 'Public Transport'] },
  { priority: 45, matchType: 'contains', pattern: 'LINKT', categoryPath: ['Transport', 'Tolls & Parking'] },
  { priority: 45, matchType: 'contains', pattern: 'LINKT', categoryPath: ['Transport', 'Tolls & Parking'] },
  { priority: 50, matchType: 'contains', pattern: 'BUNNINGS', categoryPath: ['Shopping', 'Household'] },
  { priority: 50, matchType: 'contains', pattern: 'KMART', categoryPath: ['Shopping', 'Household'] },
  { priority: 50, matchType: 'contains', pattern: 'TARGET', categoryPath: ['Shopping', 'Household'] },
  { priority: 50, matchType: 'contains', pattern: 'OFFICEWORKS', categoryPath: ['Shopping', 'Household'] },
  { priority: 50, matchType: 'contains', pattern: 'IKEA', categoryPath: ['Shopping', 'Household'] },
  { priority: 55, matchType: 'contains', pattern: 'JB HI', categoryPath: ['Shopping', 'Electronics'] },
  { priority: 55, matchType: 'contains', pattern: 'THE GOOD GUYS', categoryPath: ['Shopping', 'Electronics'] },
  { priority: 55, matchType: 'contains', pattern: 'HARVEY NORMAN', categoryPath: ['Shopping', 'Electronics'] },
  { priority: 55, matchType: 'contains', pattern: 'APPLE.COM', categoryPath: ['Shopping', 'Electronics'] },
  { priority: 60, matchType: 'contains', pattern: 'CHEMIST WAREHOUSE', categoryPath: ['Health', 'Pharmacy'] },
  { priority: 60, matchType: 'contains', pattern: 'PRICELINE', categoryPath: ['Health', 'Pharmacy'] },
  { priority: 60, matchType: 'contains', pattern: 'MEDICARE', categoryPath: ['Health', 'Medical'] },
  { priority: 60, matchType: 'contains', pattern: 'BUPA', categoryPath: ['Health', 'Health Insurance'] },
  { priority: 60, matchType: 'contains', pattern: 'MEDIBANK', categoryPath: ['Health', 'Health Insurance'] },
  { priority: 65, matchType: 'contains', pattern: 'ANYTIME FITNESS', categoryPath: ['Health', 'Fitness'] },
  { priority: 65, matchType: 'contains', pattern: 'FITNESS FIRST', categoryPath: ['Health', 'Fitness'] },
  { priority: 70, matchType: 'contains', pattern: 'NETFLIX', categoryPath: ['Subscriptions', 'Streaming'] },
  { priority: 70, matchType: 'contains', pattern: 'SPOTIFY', categoryPath: ['Subscriptions', 'Streaming'] },
  { priority: 70, matchType: 'contains', pattern: 'DISNEY', categoryPath: ['Subscriptions', 'Streaming'] },
  { priority: 70, matchType: 'contains', pattern: 'STAN.COM', categoryPath: ['Subscriptions', 'Streaming'] },
  { priority: 70, matchType: 'contains', pattern: 'YOUTUBE PREMIUM', categoryPath: ['Subscriptions', 'Streaming'] },
  { priority: 75, matchType: 'contains', pattern: 'MICROSOFT', categoryPath: ['Subscriptions', 'Software'] },
  { priority: 75, matchType: 'contains', pattern: 'ADOBE', categoryPath: ['Subscriptions', 'Software'] },
  { priority: 75, matchType: 'contains', pattern: 'GOOGLE *YOUTUBE', categoryPath: ['Subscriptions', 'Streaming'] },
  { priority: 75, matchType: 'contains', pattern: 'APPLE.COM/BILL', categoryPath: ['Subscriptions', 'Software'] },
  { priority: 80, matchType: 'contains', pattern: 'TELSTRA', categoryPath: ['Utilities', 'Mobile'] },
  { priority: 80, matchType: 'contains', pattern: 'OPTUS', categoryPath: ['Utilities', 'Mobile'] },
  { priority: 80, matchType: 'contains', pattern: 'VODAFONE', categoryPath: ['Utilities', 'Mobile'] },
  { priority: 80, matchType: 'contains', pattern: 'ORIGIN ENERGY', categoryPath: ['Utilities', 'Electricity'] },
  { priority: 80, matchType: 'contains', pattern: 'AGL ', categoryPath: ['Utilities', 'Electricity'] },
  { priority: 80, matchType: 'contains', pattern: 'ENERGYAUSTRALIA', categoryPath: ['Utilities', 'Electricity'] },
  { priority: 85, matchType: 'contains', pattern: 'ATM ', categoryPath: ['Cash Withdrawal'] },
  { priority: 85, matchType: 'contains', pattern: 'CASH WITHDRAWAL', categoryPath: ['Cash Withdrawal'] },
  { priority: 90, matchType: 'contains', pattern: 'SALARY', categoryPath: ['Income', 'Salary'] },
  { priority: 90, matchType: 'contains', pattern: 'WAGES', categoryPath: ['Income', 'Salary'] },
  { priority: 90, matchType: 'contains', pattern: 'PAYROLL', categoryPath: ['Income', 'Salary'] },
]
